version: '3.5'

services:

  jupyter:
    image: jupyter/base-notebook
    container_name: jupyter
    volumes:
    - /tmp/jupyter:/home/jupyter/
    ports:
    - 8889:8888
    command:
      jupyter-notebook --NotebookApp.token='' --NotebookApp.password=''
